// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 2/9/2026, 15:14:56
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["/Applications/XAMPP/xamppfiles/htdocs/Proyectos/Grupo K/jcdvs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/Proyectos/Grupo K/jcdvs/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/Proyectos/Grupo K/jcdvs/components/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/Proyectos/Grupo K/jcdvs/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/Proyectos/Grupo K/jcdvs/plugins/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/Proyectos/Grupo K/jcdvs/composables/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/Proyectos/Grupo K/jcdvs/utils/**/*.{js,ts,mjs}","/Applications/XAMPP/xamppfiles/htdocs/Proyectos/Grupo K/jcdvs/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/Proyectos/Grupo K/jcdvs/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/Proyectos/Grupo K/jcdvs/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","/Applications/XAMPP/xamppfiles/htdocs/Proyectos/Grupo K/jcdvs/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;